micronaut:
  application:
    name: basic-app
  server:
    cors:
      enabled: true
---
micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
---
endpoints:
  info:
    enabled: true
    sensitive: false
